# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gong < Formula
  desc "Gong"
  homepage "https://github.com/Djiit/gong"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Djiit/gong/releases/download/v0.2.0/gong_0.2.0_darwin_amd64.tar.gz"
      sha256 "06e81b0ab8c6c5e17c074ab3ec85c900bd345381abd72483b0be3f626243fdf1"

      def install
        bin.install "gong"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Djiit/gong/releases/download/v0.2.0/gong_0.2.0_darwin_arm64.tar.gz"
      sha256 "653d7d20ac274b1fee67f6fb0f27d1bd039e511ce254ec9ad0c3b801dc245898"

      def install
        bin.install "gong"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Djiit/gong/releases/download/v0.2.0/gong_0.2.0_linux_amd64.tar.gz"
        sha256 "3946958609f222a03edd26d46ab254637bf609e6a64f25f6b5426bdc92133db1"

        def install
          bin.install "gong"
        end
      end
    end
  end
end
