# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gong < Formula
  desc "Gong"
  homepage "https://github.com/Djiit/gong"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Djiit/gong/releases/download/v0.1.4/gong_0.1.4_darwin_amd64.tar.gz"
      sha256 "42788f14abba882740882ce63c5f66fe8f39d3638805a6fbb1467efbef37a01a"

      def install
        bin.install "gong"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Djiit/gong/releases/download/v0.1.4/gong_0.1.4_darwin_arm64.tar.gz"
      sha256 "958ea88d4bc1675bfb3a1df4a5b17f2ea1ecef456f9dba973169c07dc47d516a"

      def install
        bin.install "gong"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Djiit/gong/releases/download/v0.1.4/gong_0.1.4_linux_amd64.tar.gz"
        sha256 "78a79c67ce25c99fd320824b4f0b337dc82aa7cde9cedff4c47f3c630600973b"

        def install
          bin.install "gong"
        end
      end
    end
  end
end
